version: "3.8"

services:
  admin:
    image: tarik42777/admin:latest
    container_name: admin_container
    expose:
      - "80"

  client:
    image: tarik42777/client:latest
    container_name: client_container
    expose:
      - "80"

  landing:
    image: tarik42777/landing:latest
    container_name: landing_container
    expose:
      - "3000"

  backend:
    image: tarik42777/backend:latest
    container_name: backend_container
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/menu
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: menu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: tarik42777/nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    depends_on:
      - admin
      - client
      - landing
      - backend

networks:
  default:
    name: philofoody_network
    driver: bridge

volumes:
  postgres_data:
