spring:
  application:
    name: menu
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: javatarik34@gmail.com
    password: hafwbilmbimzqjzj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging:
    config: classpath:logback-${spring.profiles.active}.xml

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 604800000 # 1 week
      refresh-token:
        expiration: 24179200000 # 1 month

