name: Deploy Foody Projects

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Kodu Çek (Checkout)
      - name: Checkout code
        uses: actions/checkout@v2

      # 2) Olası Eski Docker/Containerd Paketlerini Kaldır
      - name: Remove old Docker packages
        run: |
          sudo apt-get update -y
          # Hata vermesin diye "|| true" kullanıyoruz (paket yüklü değilse de geçsin)
          sudo apt-get remove -y containerd docker docker.io runc || true
          sudo apt-get autoremove -y || true

      # 3) Resmî get.docker.com ile Docker Kur
      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com | sudo sh

      # 4) (Opsiyonel) Docker Compose kur (bazı imajlarda zaten geliyor)
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # 5) (Opsiyonel) Registry'ye login (eğer imaj push’layacaksanız)
      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # 6) (Opsiyonel) Docker Compose Build (Runner üzerinde)
      - name: Docker Compose Build
        run: |
          docker-compose -f docker-compose.yaml build

      # 7) (Opsiyonel) Docker Compose Push
      - name: Docker Compose Push
        run: |
          docker-compose -f docker-compose.yaml push

      # 8) Kodları Sunucuya Kopyala
      - name: Copy code to server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: '.'
          target: '/app/menu_0'

      # 9) Sunucuda Deploy
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /app/menu_0
            docker-compose pull        # Opsiyonel (Runner'da push yaptıysanız)
            docker-compose up -d --build

      # 10) (Opsiyonel) Nginx Restart
      - name: Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            sudo systemctl restart nginx
