name: Deploy Foody Projects

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Kodu Çek (Checkout)
      - name: Checkout code
        uses: actions/checkout@v2

      # 2) Docker + Docker Compose Kurun
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # 3) (Opsiyonel) Docker Registry'ye login
      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # 4) Docker Compose Build
      - name: Docker Compose Build
        run: |
          docker-compose -f docker-compose.yaml build

      # 5) (Opsiyonel) Docker Compose Push
      - name: Docker Compose Push
        run: |
          docker-compose -f docker-compose.yaml push

      # 6) Uzak Sunucuya SSH ile Bağlanarak Deploy
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd app
            docker-compose pull
            docker-compose up -d --build

      # 7) (Opsiyonel) Nginx Restart
      - name: Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            sudo systemctl restart nginx
