name: Deploy Foody Projects

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Kodu Çek (Checkout)
      - name: Checkout code
        uses: actions/checkout@v2

      # 2) Docker ve Docker Compose Kur (Opsiyonel: Runner üzerinde build veya test yapacaksanız)
      - name: Install Docker & Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose

      # 3) (Opsiyonel) Registry'ye Login (Eğer imaj push'lamak isterseniz)
      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # 4) (Opsiyonel) Docker Compose Build + Push (Eğer CI tarafında imaj üretip push’lamak istiyorsanız)
      - name: Docker Compose Build
        run: |
          docker-compose -f docker-compose.yaml build
      
      - name: Docker Compose Push
        run: |
          docker-compose -f docker-compose.yaml push

      # 5) Kodları Sunucuya Kopyala (appleboy/scp-action)
      - name: Copy code to server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: '.'  
          target: '/app/menu_0'

      # 6) Sunucuda Deploy (appleboy/ssh-action)
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /app/menu_0
            docker-compose pull  # Opsiyonel: Eğer CI tarafında push yaptıysanız
            docker-compose up -d --build

      # 7) (Opsiyonel) Nginx Restart vb.
      - name: Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            sudo systemctl restart nginx
