name: Deploy Foody Projects

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
      
    - name: Install Dependencies
      run: |
        npm install --prefix ./admin
        npm install --prefix ./client
        npm install --prefix ./landing

    # Build the admin project
    - name: Build Admin
      run: |
        CI=false npm run build --prefix ./admin
      env:
        REACT_APP_BASE_API_URL: ${{ secrets.REACT_APP_BASE_API_URL }}
    
    # Build the client project
    - name: Build Client
      run: |
        CI=false npm run build --prefix ./client
    
    # Build the landing project
    - name: Export Landing
      run: |
        CI=false npm run export --prefix ./landing

    # Setup Java
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    # Build Java Spring Boot project
    - name: Build Java Spring Boot Project
      run: |
        cd ./server/mono/
        mvn clean install
    
    # Deploy all projects
    - name: Deploy Projects
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        rm: true # This option will remove the files before transferring new ones
        source: "./landing/out/,./admin/build/,./client/build/,./server/mono/target/mono-0.0.1-SNAPSHOT.jar"
        target: "/var/www/foody"

    # Restart Nginx
    - name: Restart Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: sudo systemctl restart nginx
    
    # Run Java Spring Boot project
    - name: Run Java Spring Boot Project
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          cd /var/www/foody/server/mono/target/
          nohup java -jar mono-0.0.1-SNAPSHOT.jar &
